# FaceNet

In [22]:
import tensorflow as tf
import os
import matplotlib.pyplot as plt
import numpy as np

from skimage.transform import resize

In [36]:
FACENET_DIR = '/home/gaston/workspace/two-face/facenet'
MODEL_PATH = os.path.join(FACENET_DIR, 'tensorflow-101/model/facenet_model.json')
MODEL_128_PATH = os.path.join(FACENET_DIR, 'tensorflow-101/model/facenet_model_128.json')
WEIGHTS_PATH = os.path.join(FACENET_DIR, 'facenet_weights.h5')


PERSON_1_IMG_1 = '/home/gaston/workspace/datasets/CASIA-WebFace/CASIA-WebFace/data/test/0000045/001.jpg'
PERSON_1_IMG_2 = '/home/gaston/workspace/datasets/CASIA-WebFace/CASIA-WebFace/data/test/0000045/002.jpg'
PERSON_2_IMG_1 = '/home/gaston/workspace/datasets/CASIA-WebFace/CASIA-WebFace/data/test/0000099/001.jpg'
PERSON_2_IMG_2 = '/home/gaston/workspace/datasets/CASIA-WebFace/CASIA-WebFace/data/test/0000099/002.jpg'

PERSON_3_IMG_1 = '/home/gaston/workspace/datasets/CASIA-WebFace/CASIA-WebFace/data/test/0000157/007.jpg'


In [40]:
#facenet model structure: https://github.com/serengil/tensorflow-101/blob/master/model/facenet_model.json
model = tf.keras.models.model_from_json(open(MODEL_PATH, "r").read())

#pre-trained weights https://drive.google.com/file/d/1971Xk5RwedbudGgTIrGAL4F7Aifu7id1/view?usp=sharing
model.load_weights(WEIGHTS_PATH)
 
model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 160, 160, 3)  0                                            
__________________________________________________________________________________________________
Conv2d_1a_3x3 (Conv2D)          (None, 79, 79, 32)   864         input_1[0][0]                    
__________________________________________________________________________________________________
Conv2d_1a_3x3_BatchNorm (BatchN (None, 79, 79, 32)   96          Conv2d_1a_3x3[0][0]              
__________________________________________________________________________________________________
Conv2d_1a_3x3_Activation (Activ (None, 79, 79, 32)   0           Conv2d_1a_3x3_BatchNorm[0][0]    
__________________________________________________________________________________________________
Conv2d_2a_

In [46]:
#facenet model structure: https://github.com/serengil/tensorflow-101/blob/master/model/facenet_model.json
model_128 = tf.keras.models.model_from_json(open(MODEL_128_PATH, "r").read())

#pre-trained weights https://drive.google.com/file/d/1971Xk5RwedbudGgTIrGAL4F7Aifu7id1/view?usp=sharing
model_128.load_weights(WEIGHTS_PATH)
 
model_128.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 128, 128, 3)  0                                            
__________________________________________________________________________________________________
Conv2d_1a_3x3 (Conv2D)          (None, 63, 63, 32)   864         input_1[0][0]                    
__________________________________________________________________________________________________
Conv2d_1a_3x3_BatchNorm (BatchN (None, 63, 63, 32)   96          Conv2d_1a_3x3[0][0]              
__________________________________________________________________________________________________
Conv2d_1a_3x3_Activation (Activ (None, 63, 63, 32)   0           Conv2d_1a_3x3_BatchNorm[0][0]    
__________________________________________________________________________________________________
Conv2d_2a_

In [47]:
def fix_image_encoding(image):
  if (image.ndim == 2):
    # Add new dimension for channels
    image = image[:, :, np.newaxis]
  if (image.shape[-1] == 1):
    # Convert greyscale to RGB
    image = np.concatenate((image,) * 3, axis=-1)
  return image

In [66]:
def preprocess_image(image_file_path, size):
  image_file = tf.gfile.GFile(image_file_path, mode='rb')
  image = plt.imread(image_file)
  image = fix_image_encoding(image)
  image = resize(image, (size, size))
  image = np.expand_dims(image, axis=0)
  image = image*2.0 - 1.0
  return image

In [67]:
img_1_1_128 = preprocess_image(PERSON_1_IMG_1, 128)
img_1_2_128 = preprocess_image(PERSON_1_IMG_2, 128)
img_2_1_128 = preprocess_image(PERSON_2_IMG_1, 128)
img_2_2_128 = preprocess_image(PERSON_2_IMG_2, 128)
img_3_1_128 = preprocess_image(PERSON_3_IMG_1, 128)

In [70]:
print(img_1_1_128)

[[[[-0.12604167 -0.39270833 -0.40055147]
   [-0.13571011 -0.39226649 -0.40347972]
   [-0.20069556 -0.43598968 -0.45167595]
   ...
   [-0.11004902 -0.62492053 -0.38709262]
   [-0.03308824 -0.55857843 -0.31544118]
   [ 0.02408088 -0.5096201  -0.26648284]]

  [[-0.1278057  -0.39447237 -0.40231551]
   [-0.13249799 -0.38905436 -0.4002676 ]
   [-0.1904991  -0.42579322 -0.44147949]
   ...
   [-0.10575645 -0.61219028 -0.38700645]
   [-0.04622348 -0.55775936 -0.33002451]
   [ 0.01073596 -0.51138413 -0.27835717]]

  [[-0.13014706 -0.39681373 -0.40465686]
   [-0.12481283 -0.3813692  -0.39258243]
   [-0.17231876 -0.40761288 -0.42329915]
   ...
   [-0.10174537 -0.59586301 -0.38409831]
   [-0.06819853 -0.56715686 -0.35539216]
   [-0.0328216  -0.53984997 -0.32555147]]

  ...

  [[ 0.52156863 -0.58431373  0.23921569]
   [ 0.52156863 -0.58431373  0.23137255]
   [ 0.52156863 -0.58431373  0.23137255]
   ...
   [-0.69964719 -0.54462268 -0.58867906]
   [-0.70079657 -0.57769943 -0.6185116 ]
   [-0.71090686 

In [68]:
pred_1_128 = model_128.predict(img_1_1_128)[0,:]
pred_2_128 = model_128.predict(img_1_2_128)[0,:]
pred_3_128 = model_128.predict(img_2_1_128)[0,:]
pred_4_128 = model_128.predict(img_2_2_128)[0,:]

pred_5_128 = model_128.predict(img_3_1_128)[0,:]

In [71]:
print(len(pred_5_128))

128


In [55]:
def findEuclideanDistance(source_representation, test_representation):
 euclidean_distance = source_representation - test_representation
 euclidean_distance = np.sum(np.multiply(euclidean_distance, euclidean_distance))
 euclidean_distance = np.sqrt(euclidean_distance)
 return euclidean_distance / len(source_representation)

In [72]:
print(findEuclideanDistance(pred_1_128, pred_2_128))
print(findEuclideanDistance(pred_3_128, pred_4_128))

print()
print(findEuclideanDistance(pred_1_128, pred_3_128))
print(findEuclideanDistance(pred_1_128, pred_4_128))

print()
print(findEuclideanDistance(pred_5_128, pred_1_128))
print(findEuclideanDistance(pred_5_128, pred_2_128))

print()
print(findEuclideanDistance(pred_5_128, pred_3_128))
print(findEuclideanDistance(pred_5_128, pred_4_128))




0.06587011367082596
0.07851880043745041

0.1339871883392334
0.13015039265155792

0.09475310146808624
0.08743075281381607

0.09438568353652954
0.09199479222297668


In [73]:
img_1_1 = preprocess_image(PERSON_1_IMG_1, 160)
img_1_2 = preprocess_image(PERSON_1_IMG_2, 160)
img_2_1 = preprocess_image(PERSON_2_IMG_1, 160)
img_2_2 = preprocess_image(PERSON_2_IMG_2, 160)
img_3_1 = preprocess_image(PERSON_3_IMG_1, 160)


/home/gaston/workspace/virtualenvs/tf-gpu/lib/python3.5/site-packages/skimage/transform/_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
/home/gaston/workspace/virtualenvs/tf-gpu/lib/python3.5/site-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "


In [75]:
print(img_1_1)

[[[[-0.13063725 -0.39730392 -0.40514706]
   [-0.11372549 -0.38039216 -0.38823529]
   [-0.17916667 -0.41911765 -0.43480392]
   ...
   [-0.07009804 -0.59379596 -0.35155484]
   [-0.01470588 -0.54019608 -0.29705882]
   [ 0.02867647 -0.50808824 -0.26495098]]

  [[-0.13063725 -0.39730392 -0.40514706]
   [-0.11372549 -0.38039216 -0.38823529]
   [-0.17352941 -0.41348039 -0.42916667]
   ...
   [-0.07402727 -0.58528646 -0.34926471]
   [-0.02028952 -0.54577972 -0.30264246]
   [ 0.0191636  -0.50808824 -0.26495098]]

  [[-0.13627451 -0.40294118 -0.41078431]
   [-0.11103707 -0.37770374 -0.38554687]
   [-0.16439185 -0.40434283 -0.42002911]
   ...
   [-0.07941176 -0.58007812 -0.36831342]
   [-0.04315257 -0.54656863 -0.33407629]
   [-0.00424326 -0.52009804 -0.30138634]]

  ...

  [[ 0.51691176 -0.58897059  0.23455882]
   [ 0.51691176 -0.58897059  0.22794118]
   [ 0.51691176 -0.58897059  0.22671569]
   ...
   [-0.71911765 -0.57751991 -0.64131434]
   [-0.71373315 -0.59460784 -0.66275276]
   [-0.71544118 

In [74]:
pred_1 = model.predict(img_1_1)[0,:]
pred_2 = model.predict(img_1_2)[0,:]
pred_3 = model.predict(img_2_1)[0,:]
pred_4 = model.predict(img_2_2)[0,:]

pred_5 = model.predict(img_3_1)[0,:]

In [76]:
print(len(pred_1))

128


In [77]:
print(findEuclideanDistance(pred_1, pred_2))
print(findEuclideanDistance(pred_3, pred_4))

print()
print(findEuclideanDistance(pred_1, pred_3))
print(findEuclideanDistance(pred_1, pred_4))

print()
print(findEuclideanDistance(pred_5, pred_1))
print(findEuclideanDistance(pred_5, pred_2))

print()
print(findEuclideanDistance(pred_5, pred_3))
print(findEuclideanDistance(pred_5, pred_4))

0.07255291193723679
0.07758000493049622

0.1185019388794899
0.12128172069787979

0.1163187101483345
0.10997657477855682

0.10901172459125519
0.10875829309225082
